# Generated by Django 4.1.1 on 2022-10-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='jabatan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
