# Generated by Django 4.1.1 on 2022-10-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0002_dosen_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='fakultas',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
