# Generated by Django 4.1.1 on 2022-10-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0003_dosen_fakultas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='jabatan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nama',
            field=models.CharField(max_length=100),
        ),
    ]
