# Generated by Django 4.1.1 on 2022-10-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pimpinan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50)),
                ('nip', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100, null=True)),
                ('fakultas', models.CharField(max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
