# Generated by Django 4.1.1 on 2022-10-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fkip', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fkip',
        ),
    ]
