# Generated by Django 4.1.1 on 2022-10-04 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_mahasiswa_delete_dosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='photo',
        ),
    ]
